# Generated by Django 6.0.3 on 2026-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
