# Generated by Django 6.0.3 on 2026-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_tutor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
