# Generated by Django 6.0.3 on 2026-05-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_complemento_user_expedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('disabled_by_attempts', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
