# Generated by Django 6.0.3 on 2026-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_paralelo_options_alter_paralelo_cupo_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
