# Generated by Django 6.0.3 on 2026-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_grado_estado_nivel_estado_paralelo_estado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grado',
            name='unique_grado_por_nivel',
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto')], max_length=50),
        ),
    ]
