# Generated by Django 6.0.3 on 2026-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_requisito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadocumento',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregadocumento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_documental',
            field=models.CharField(choices=[('completa', 'Completa'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_limite_documentos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
