# Generated by Django 6.0.3 on 2026-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_entregadocumento_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
    ]
